package myp;
// Generated Nov 1, 2014 11:36:25 AM by Hibernate Tools 4.3.1



/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private String un;
     private String up;

    public Emp() {
    }

    public Emp(String un, String up) {
       this.un = un;
       this.up = up;
    }
   
    public String getUn() {
        return this.un;
    }
    
    public void setUn(String un) {
        this.un = un;
    }
    public String getUp() {
        return this.up;
    }
    
    public void setUp(String up) {
        this.up = up;
    }
}