package myp;
// Generated Nov 1, 2014 11:36:25 AM by Hibernate Tools 4.3.1



/**
 * Tutorial generated by hbm2java
 */
public class Tutorial  implements java.io.Serializable {


     private Integer id;
     private String sortdes;
     private String longdes;
     private String pageurl;

    public Tutorial() {
    }

    public Tutorial(String sortdes, String longdes, String pageurl) {
       this.sortdes = sortdes;
       this.longdes = longdes;
       this.pageurl = pageurl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSortdes() {
        return this.sortdes;
    }
    
    public void setSortdes(String sortdes) {
        this.sortdes = sortdes;
    }
    public String getLongdes() {
        return this.longdes;
    }
    
    public void setLongdes(String longdes) {
        this.longdes = longdes;
    }
    public String getPageurl() {
        return this.pageurl;
    }
    
    public void setPageurl(String pageurl) {
        this.pageurl = pageurl;
    }




}


